### PR TITLE
Properly handle Access vs. Create timestamps for CP/M 3.

### PR DESCRIPTION
**Pull request by durgadas311**
Not sure if this is the right place to submit changes, but here is a fix for timestamp handling on CP/M 3 disks, to handle the user choice of Access vs. Create timestamps.

### CODE REVIEW

**Comment by durgadas311** [comment]
This second commit may require more discussion. It allows the format to be specified by name (as usual) or actual diskdef format text. I found this particularly handy for handling Magnolia Microsystems SASI disk images, which have a user-customized partition table and DPBs saved on each drive, but also to support H89 emulator images for the plethora of obscure floppy formats supported by MMS. I wrote a program to examine the disk image and generate an appropriate diskdef on-the-fly, and pass that directly to the respective cpmtools command.

I'm not sure why both commits ended up in the same pull request. If you know how to separate those, let me know.

**Comment by rexut** [comment]
> Not sure if this is the right place to submit changes, ...

Not really, this project is an unofficial mirrored repository of the original code made by Michael Haardt, see: http://www.moria.de/~michael/cpmtools/

First of all you should inform Michael directly about your changes and discuss the technical details with him. I'm not able to review any thing related to CP/M 3.0 (my historical experiences was ending with CP/M 2.2). Here is the contact: http://www.moria.de/~michael/

But anyway thanks for your commit. I'll let the PR open so perhaps you can make any upcoming discussion here in this thread if needed. As long as I can see, Michael is still working on the cpmtools, there is a version 2.21-snapshot dated from 2017-01-28, see: http://www.moria.de/~michael/cpmtools/files/

**Comment by durgadas311** [comment]
Thanks, I've emailed the patches to michael.

**Comment by durgadas311** [comment]
Michael added the first patch, and I have re-submitted the second. These are now represented in branches 'accesstime' and 'embedded_fmt', respectively in my fork of your repository.

**Pull request closed without merging**
